name: 03 - Branch Filter

on:
   workflow_dispatch:        #push:
    #branches:
      #- main
      #- 'release/**'

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Show what triggered me
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref_name }}"
          echo "Triggered by: ${{ github.actor }}"
